# Generated by Django 4.2.8 on 2023-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('movieName', models.CharField(max_length=100)),
                ('movieGenre', models.CharField(max_length=100)),
                ('movieDescription', models.CharField(max_length=100)),
                ('moviePoster', models.CharField(max_length=100)),
            ],
        ),
    ]
