# Generated by Django 4.2.8 on 2023-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='moviePoster',
            field=models.URLField(),
        ),
    ]
