# Generated by Django 4.2.8 on 2023-12-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='RegistrationNo',
            new_name='Registration_No',
        ),
    ]
