# Generated by Django 4.2.8 on 2023-12-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/placeholder.jpg', upload_to='images/'),
        ),
    ]
